version: '3.4'

services:
  hyre-bootstrapper:
    image: ${DOCKER_REGISTRY-}hyrebootstrapper:latest
    container_name: hyre-api
    build:
      context: .
      dockerfile: src/Bootstrapper/Hyre.Bootstrapper/Dockerfile
    depends_on:
      - hyre-database
    networks:
      - hyre

  hyre-database:
    image: postgres
    container_name: hyre-db
    hostname: hyre-db
    shm_size: '4gb'
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: hyre-db
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - hyre
  

volumes:
  pg-data:
    driver: local

networks:
  hyre:
    external: true
    name: hyre-network