// <auto-generated />
using System;
using Hyre.Modules.Jobs.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hyre.Modules.Jobs.Infrastructure.Migrations
{
    [DbContext(typeof(JobsRepositoryContext))]
    partial class JobsRepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("jobs")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hyre.Modules.Jobs.Core.Entities.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("JobOpportunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_opportunity_id");

                    b.HasKey("Id")
                        .HasName("pk_candidates");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_candidates_email");

                    b.HasIndex("JobOpportunityId")
                        .HasDatabaseName("ix_candidates_job_opportunity_id");

                    b.ToTable("candidates", "jobs");
                });

            modelBuilder.Entity("Hyre.Modules.Jobs.Core.Entities.JobOpportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_job_opportunities");

                    b.ToTable("job_opportunities", "jobs");
                });

            modelBuilder.Entity("Hyre.Modules.Jobs.Core.Entities.Candidate", b =>
                {
                    b.HasOne("Hyre.Modules.Jobs.Core.Entities.JobOpportunity", "JobOpportunity")
                        .WithMany("Candidates")
                        .HasForeignKey("JobOpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_candidates_job_opportunities_job_opportunity_id");

                    b.OwnsOne("Hyre.Modules.Jobs.Core.ValueObjects.Candidates.CandidateName", "Name", b1 =>
                        {
                            b1.Property<Guid>("CandidateId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("last_name");

                            b1.Property<string>("MiddleName")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("middle_name");

                            b1.HasKey("CandidateId");

                            b1.ToTable("candidates", "jobs");

                            b1.WithOwner()
                                .HasForeignKey("CandidateId")
                                .HasConstraintName("fk_candidates_candidates_id");
                        });

                    b.Navigation("JobOpportunity");

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Hyre.Modules.Jobs.Core.Entities.JobOpportunity", b =>
                {
                    b.OwnsOne("Hyre.Modules.Jobs.Core.ValueObjects.JobOpportunities.JobOpportunityContract", "Contract", b1 =>
                        {
                            b1.Property<Guid>("JobOpportunityId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("MaxSalary")
                                .HasColumnType("numeric")
                                .HasColumnName("contract_max_salary");

                            b1.Property<decimal>("MinSalary")
                                .HasColumnType("numeric")
                                .HasColumnName("contract_min_salary");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("contract_type");

                            b1.HasKey("JobOpportunityId");

                            b1.ToTable("job_opportunities", "jobs");

                            b1.WithOwner()
                                .HasForeignKey("JobOpportunityId")
                                .HasConstraintName("fk_job_opportunities_job_opportunities_id");
                        });

                    b.OwnsOne("Hyre.Modules.Jobs.Core.ValueObjects.JobOpportunities.JobOpportunityLocation", "Location", b1 =>
                        {
                            b1.Property<Guid>("JobOpportunityId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("location_city");

                            b1.Property<string>("State")
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("location_state");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("location_type");

                            b1.HasKey("JobOpportunityId");

                            b1.ToTable("job_opportunities", "jobs");

                            b1.WithOwner()
                                .HasForeignKey("JobOpportunityId")
                                .HasConstraintName("fk_job_opportunities_job_opportunities_id");
                        });

                    b.OwnsOne("Hyre.Modules.Jobs.Core.ValueObjects.JobOpportunities.JobOpportunityRequirements", "Requirements", b1 =>
                        {
                            b1.Property<Guid>("JobOpportunityId")
                                .HasColumnType("uuid");

                            b1.Property<string[]>("Values")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasAnnotation("Relational:JsonPropertyName", "values");

                            b1.HasKey("JobOpportunityId");

                            b1.ToTable("job_opportunities", "jobs");

                            b1.ToJson("requirements");

                            b1.WithOwner()
                                .HasForeignKey("JobOpportunityId")
                                .HasConstraintName("fk_job_opportunities_job_opportunities_id");
                        });

                    b.Navigation("Contract")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Requirements");
                });

            modelBuilder.Entity("Hyre.Modules.Jobs.Core.Entities.JobOpportunity", b =>
                {
                    b.Navigation("Candidates");
                });
#pragma warning restore 612, 618
        }
    }
}
